version: "3"
services:

  odoo:
    image: odoo:16.0
    ports:
      - 8070:8070
    container_name: odoo16
    environment:
      - DB_ENV_POSTGRES_USER=odoo
      - DB_ENV_POSTGRES_PASSWORD=odoo
    links:
      - db:db
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./filestore:/var/lib/odoo
    network_mode: "bridge"

  db:
    image: postgres:12.0
    container_name: odoo16_db
    hostname: odoo16_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./data:/var/lib/postgresql/data
    network_mode: "bridge"
